server:
  port: 8382
a1:
  host: "policy-agent"
  port: 8081
dc:
  host: "localhost"
  port: 8087
  version: "v1"
scd:
  prefix: "emergency"
  slot: 10
  count: 12
logging:
  level:
    org:
      springframework: DEBUG
  logging.file.name: logs/rapp-sleepingcelldetector.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
