server:
  port: 8382
a1:
  protocol: "http"
  host: "policy-agent"
  port: 8081
datacollector:
  protocol: "http"
  host: "localhost"
  port: 8087
  version: "v1"
sleepingcelldetector:
  prefix: "emergency"
  slot: 10
  count: 12
logging:
  level:
    org:
      springframework: DEBUG
  logging.file.name: logs/rapp-sleepingcelldetector.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
spring:
  jackson:
    default-property-inclusion: non_null
